language: php
php:
  - 5.4
  - 5.5
  - 5.6

env: TEST_USER=root TEST_PASSWORD= TEST_DATABASE=caribu_test

install:
    composer install


before_script:
  - mysql -e 'create database caribu_test'

script:
  - phpcs
  - pdepend
  - phpmd
  - phpunit